import type { Property } from "./types"
export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Loft",
    price: 850000,
    location: {
      address: "123 Main Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    images: ["/images/h1.png", "/images/modern-downtown.png", "/images/spacious-city.png"],
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1200,
    propertyType: "apartment",
    description:
      "Stunning modern loft in the heart of downtown with exposed brick walls, high ceilings, and panoramic city views. Recently renovated with premium finishes throughout.",
    features: ["Exposed Brick", "High Ceilings", "City Views", "Modern Kitchen", "In-unit Laundry", "Parking"],
    yearBuilt: 1920,
    status: "for-sale",
    agent: {
      name: "Sarah Johnson",
      phone: "(555) 123-4567",
      email: "sarah@realestate.com",
      image: "/images/professionals-women-realtor.png",
    },
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: "2",
    title: "Luxury Family Home",
    price: 1250000,
    location: {
      address: "456 Oak Avenue",
      city: "Palo Alto",
      state: "CA",
      zipCode: "94301",
      coordinates: { lat: 37.4419, lng: -122.143 },
    },
    images: ["/images/luxury-house.png", "/images/elegant-dinning-room.png", "/images/luxurious-master-suite.png"],
    bedrooms: 4,
    bathrooms: 3,
    squareFootage: 2800,
    propertyType: "house",
    description:
      "Beautiful family home in prestigious neighborhood. Features spacious rooms, gourmet kitchen, and beautifully landscaped backyard perfect for entertaining.",
    features: ["Gourmet Kitchen", "Hardwood Floors", "Fireplace", "Large Backyard", "Garage", "Walk-in Closets"],
    yearBuilt: 2015,
    status: "for-sale",
    agent: {
      name: "Michael Chen",
      phone: "(555) 987-6543",
      email: "michael@realestate.com",
      image: "/images/professional-asian-man.png",
    },
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
  },
  {
    id: "3",
    title: "Cozy Studio Apartment",
    price: 2800,
    location: {
      address: "789 Pine Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94108",
      coordinates: { lat: 37.7849, lng: -122.4094 },
    },
    images: ["/images/cozy-studio-murphy-bed.png", "/images/compact-kitchen.png", "/images/apartment-view.png"],
    bedrooms: 0,
    bathrooms: 1,
    squareFootage: 450,
    propertyType: "apartment",
    description:
      "Charming studio apartment in Nob Hill with efficient layout and stunning city views. Perfect for young professionals.",
    features: ["City Views", "Murphy Bed", "Compact Kitchen", "Hardwood Floors", "Natural Light"],
    yearBuilt: 1960,
    status: "for-rent",
    agent: {
      name: "Emily Rodriguez",
      phone: "(555) 456-7890",
      email: "emily@realestate.com",
      image: "/images/professional-realtor-women.png",
    },
    createdAt: "2024-01-12",
    updatedAt: "2024-01-19",
  },
  {
    id: "4",
    title: "Waterfront Condo",
    price: 950000,
    location: {
      address: "321 Bay Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94133",
      coordinates: { lat: 37.8049, lng: -122.4194 },
    },
    images: ["/images/waterfront-conad.png", "/images/modern-bathroom.png", "/images/balcony-water.png"],
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1100,
    propertyType: "condo",
    description:
      "Spectacular waterfront condo with panoramic bay views. Features modern amenities and access to building facilities including gym and rooftop deck.",
    features: ["Bay Views", "Balcony", "Gym Access", "Rooftop Deck", "Concierge", "Parking"],
    yearBuilt: 2018,
    status: "for-sale",
    agent: {
      name: "David Kim",
      phone: "(555) 234-5678",
      email: "david@realestate.com",
      image: "/images/professional-asian-man.png",
    },
    createdAt: "2024-01-08",
    updatedAt: "2024-01-16",
  },
  {
    id: "5",
    title: "Suburban Townhouse",
    price: 750000,
    location: {
      address: "654 Maple Drive",
      city: "San Mateo",
      state: "CA",
      zipCode: "94403",
      coordinates: { lat: 37.563, lng: -122.3255 },
    },
    images: ["/images/suburbna-town.png", "/images/open-concept-living-room.png", "/images/modern-townhouse-kitchen.png"],
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1600,
    propertyType: "townhouse",
    description:
      "Well-maintained townhouse in family-friendly neighborhood. Features open floor plan, private patio, and attached garage.",
    features: ["Open Floor Plan", "Private Patio", "Attached Garage", "Storage", "Near Schools", "Quiet Street"],
    yearBuilt: 2010,
    status: "for-sale",
    agent: {
      name: "Lisa Thompson",
      phone: "(555) 345-6789",
      email: "lisa@realestate.com",
      image: "/images/agent1.png",
    },
    createdAt: "2024-01-05",
    updatedAt: "2024-01-14",
  },
  {
    id: "6",
    title: "Penthouse Suite",
    price: 2200000,
    location: {
      address: "987 Luxury Lane",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      coordinates: { lat: 37.7849, lng: -122.4194 },
    },
    images: [
      "/images/l1.png",
      "/images/l2.png",
      "/images/l3.png",
    ],
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 2200,
    propertyType: "condo",
    description:
      "Exclusive penthouse suite with private rooftop terrace and 360-degree city views. Premium finishes and smart home technology throughout.",
    features: ["Rooftop Terrace", "360° Views", "Smart Home", "Wine Cellar", "Private Elevator", "Concierge"],
    yearBuilt: 2020,
    status: "for-sale",
    agent: {
      name: "Robert Wilson",
      phone: "(555) 567-8901",
      email: "robert@realestate.com",
      image: "/images/asian-realtor.png",
    },
    createdAt: "2024-01-01",
    updatedAt: "2024-01-21",
  },
]
